- name: Install Brave APT key
  apt_key:
    state: present
    url: "https://brave-browser-apt-release.s3.brave.com/brave-core.asc"

- name: Add Brave APT sources
  apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present

- name: Add Brave browser
  apt:
    name: brave-browser
    state: present
