---

- name: Add Google key
  get_url:
    force: true
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    dest: /etc/apt/trusted.gpg.d/google-chrome.asc
    mode: '0644'
  # thanks to https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
  # for this get_url strategy

- name: Add Google Chrome Repository
  lineinfile:
    create: yes
    dest: /etc/apt/sources.list.d/google-chrome.list
    regexp: ^deb.*
    line: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Update APT after manually adding Google Chrome repo
  apt: update_cache=yes

- name: Install Google Chrome
  apt: name=google-chrome-stable state=latest update_cache=yes
