- name: Install Gnome
  apt: name=gnome state=latest

- name: Install Cinnamon Desktop Environment
  apt:
    state: latest
    name:
      - cinnamon-desktop-environment
      - cinnamon-screensaver
      - xscreensaver-data
      - xscreensaver-data-extra
      - xscreensaver-gl
      - xscreensaver-gl-extra

#
# Not sure if this is entirely necessary. It was originally part of
# the stuff necessary to bootstrap the Cinnamon environment.
#
- name: Install kwallet
  apt: name="{{ item }}" state=latest
  with_items:
    - kwalletmanager
    - libpam-kwallet-common
    - libpam-kwallet4
    - libpam-kwallet5
