- name: Install Gnome
  apt: name=gnome state=latest

- name: Install Gnome Desktop
  apt: name=ubuntu-gnome-desktop state=latest

- name: Install Gnome packages (16.04)
  apt:
    name:
      - gnome-shell-extensions
      - gnome-software
      - gnome-tweak-tool
      - gnome-tweaks
