---

- name: Install helpful utilities
  apt:
    state: latest
    name:
      - alsa-utils
      - deepin-screenshot
      - gkrellm
      - gkrellm-cpufreq
      - gkrellm-x86info
      - sshfs
      - synaptic

- name: Install Terminator
  apt: name=terminator state=latest

- apt: name=ubuntu-restricted-extras state=latest
  when: ansible_distribution == "Ubuntu"

- apt: name=ubuntu-restricted-addons state=latest
  when: ansible_distribution == "Ubuntu"
